<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <AssemblyName>IdempotentCookie.Email.DependencyInjection.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.0.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IdempotentCookie.Email.Infrastructure\IdempotentCookie.Email.Infrastructure.csproj" />
    <ProjectReference Include="..\IdempotentCookie.Email.Mailgun\IdempotentCookie.Email.Mailgun.csproj" />
    <ProjectReference Include="..\IdempotentCookie.Email.Office365\IdempotentCookie.Email.Office365.csproj" />
    <ProjectReference Include="..\IdempotentCookie.Email.SendGrid\IdempotentCookie.Email.SendGrid.csproj" />
    <ProjectReference Include="..\IdempotentCookie.Email.Smtp\IdempotentCookie.Email.Smtp.csproj" />
  </ItemGroup>

</Project>