<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\IdempotentCookie.Email.Mailgun\IdempotentCookie.Email.Mailgun.csproj" />
		<ProjectReference Include="..\IdempotentCookie.Email.Office365\IdempotentCookie.Email.Office365.csproj" />
	</ItemGroup>

</Project>